# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        ObservationBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_OBS: ROLE_USER
        ROLE_NATURALISTE: ROLE_OBS,ROLE_USER
        ROLE_ADMIN: ROLE_NATURALISTE, ROLE_OBS, ROLE_USER

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
          id: user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
              login_path: user_connect
              check_path: user_login
              remember_me: true
            logout:
                path: user_logout
                target: homepage
            # connection avec google et facebook
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        user_connect
                use_forward:       false
                failure_path:      user_connect
                oauth_user_provider:
                    service: user_provider
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/user/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/observation, roles: ROLE_USER }
        - { path: ^/user/profil, roles: ROLE_USER }
        - {path: ^/user/observation, roles: ROLE_NATURALISTE }
        - {path: ^/user/stars, roles: ROLE_OBS }
        - {path: ^/observation/list, roles: ROLE_USER }