user:
    prefix: user
    resource: 'Routing/user.yml'

bird:
    prefix: /bird
    resource: 'Routing/bird.yml'

observation:
    prefix: /observation
    resource: 'Routing/observation.yml'

star:
    prefix: /star
    resource: 'Routing/star.yml'

blog:
    prefix: /asso
    resource: 'Routing/blog.yml'
contact:
    prefix: /contact
    resource: Routing/contact.yml

homepage:
    path:     /
    defaults: { _controller: ObservationBundle:Default:index }
    method: [GET]

faq_edit:
    path: /faq/edit/{page}
    defaults:
        _controller: ObservationBundle:Default:editFaq
    method: [GET, POST]
faq:
    path: /faq
    defaults:
        _controller: ObservationBundle:Default:faq
    method: [GET]


newsletter:
    prefix: /newsletter
    resource: Routing/newsletter.yml

