user:
    prefix: user
    resource: 'Routing/user.yml'

bird:
    prefix: /bird
    resource: 'Routing/bird.yml'

observation:
    prefix: /observation
    resource: 'Routing/observation.yml'

homepage:
    path:     /
    defaults: { _controller: ObservationBundle:Default:index }

asso:
    path: /asso
    defaults:
      _controller: ObservationBundle:Default:index

contact:
    path: /contact
    defaults:
        _controller: ObservationBundle:Default:contact

faq:
    path: /faq
    defaults:
        _controller: ObservationBundle:Default:faq