user:
    prefix: user
    resource: 'Routing/user.yml'

bird:
    prefix: /bird
    resource: 'Routing/bird.yml'

observation:
    prefix: /observation
    resource: 'Routing/observation.yml'

star:
    prefix: /star
    resource: 'Routing/star.yml'

blog:
    prefix: /blog
    resource: 'Routing/blog.yml'
contact:
    prefix: /contact
    resource: Routing/contact.yml
homepage:
    path:     /
    defaults: { _controller: ObservationBundle:Default:index }

asso:
    path: /asso
    defaults:
      _controller: ObservationBundle:Default:index


faq:
    path: /faq
    defaults:
        _controller: ObservationBundle:Default:faq

newsletter:
    prefix: /newsletter
    resource: Routing/newsletter.yml