services:
#    observation.example:
#        class: ObservationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    observation.user.mailer:
        class: ObservationBundle\Mailer\UserMailer
        arguments: ['%mandrill_api_key%', '@router']

    observation.contact.mailer:
        class: ObservationBundle\Mailer\ContactMailer
        arguments: ['%mandrill_api_key%', '@router']

    observation.newsletter_listing:
        class: ObservationBundle\Mailer\NewsLetter
        arguments: ['%mailchimp_api_key%', '%mailchimp_list_id%']

    observation.captured.event_subscriber:
        class: ObservationBundle\EventListener\ObservationSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: kernel.event_subscriber }

    observation.event_listener:
        class:  ObservationBundle\EventListener\ObservationListener

    user.captured.event_subscriber:
        class: ObservationBundle\EventListener\UserSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - {name: kernel.event_subscriber }
