asso_mention_legal_edit:
    path: /{page}/edit
    defaults:
        _controller: ObservationBundle:Default:editMention
    methods: [GET, POST]
    requirements:
        -page: mentions-legales

asso_mention_legal:
    path: /{page}
    defaults:
        _controller: ObservationBundle:Default:mention
    methods: [GET]
    requirements:
        -page: mentions-legales


