

billet_create:
  path: /billet/create
  defaults:
    _controller: ObservationBundle:Blog:create
    requirements:
      _method:  GET|POST


billet_edit:
  path: /billet/{id}/edit
  defaults:
    _controller: ObservationBundle:Blog:edit
  requirements:
    -page: blog
    _method: GET|PSOT

blog_view:
   path: /
   defaults:
     _controller: ObservationBundle:Blog:view
   requirements:
     -page: blog
     _method: GET|POST
