

billet_create:
  path: /billet/create
  defaults:
    _controller: ObservationBundle:Blog:create


billet_edit:
  path: /billet/{id}/edit
  defaults:
    _controller: ObservationBundle:Blog:edit
  requirements:
    -page: blog

blog_view:
   path: /
   defaults:
     _controller: ObservationBundle:Blog:view
   requirements:
     -page: blog