contact_resend:
  path: /{id}/resend
  defaults:
    _controller: ObservationBundle:Contact:resend

contact_received:
  path: /{id}/received
  defaults:
    _controller: ObservationBundle:Contact:received

contact_answered:
  path: /{id}/answered
  defaults:
    _controller: ObservationBundle:Contact:answered

contact_refresh:
  path: /refresh
  defaults:
    _controller: ObservationBundle:Contact:refresh
contact_message:
    path: /contact
    defaults:
        _controller: ObservationBundle:Default:contact