observation_page:
    path: /list/{status}/{page}/{all}
    defaults:
      _controller:  ObservationBundle:Observation:pagination
    requirements:
      -status: true/false
      -page: \d+
      -all:  true|false

observation_bird_page:
    path: /bird_list/{id}/{page}
    defaults:
      _controller: ObservationBundle:Observation:birdPagination
    requirements:
      -page: \d+

observation_add:
    path: /add
    defaults:
      _controller: ObservationBundle:Observation:add

observation_validate:
    path: /{id}/validate
    defaults:
      _controller:  ObservationBundle:Observation:validate

observation_unvalidate:
    path: /{id}/unvalidate
    defaults:
      _controller: ObservationBundle:Observation:unvalide

observation_view:
    path: /{id}/view
    defaults:
      _controller: ObservationBundle:Observation:view

observation_locations:
    path: /{id}/locations
    defaults:
      _controller: ObservationBundle:Observation:locations
