user_login:
    path: /login
    defaults:
      _controller: ObservationBundle:User:login
user_logout:
    path: /logout

user_forgot_password:
    path: /reset
    defaults:
      _controller: ObservationBundle:User:reset

user_link_forgot:
    path: /reset/{token}
    defaults:
      _controller: ObservationBundle:User:resetPassword
      token: \.+

user_change_password:
    path: /change_password
    defaults:
      _controller: ObservationBundle:User:changePassword

user_profil:
    path: /profil
    defaults:
      _controller: ObservationBundle:User:profil

user_connect:
    path: /connect
    defaults:
        _controller: ObservationBundle:User:connect

user_my_observations:
    path: /my_observations
    defaults:
        _controller: ObservationBundle:User:myObservations

user_observations:
    path: /observations
    defaults:
        _controller: ObservationBundle:User:observations

user_stars:
    path: /stars
    defaults:
        _controller: ObservationBundle:User:stars

user_change_avatar:
    path: /avatar/change
    defaults:
      _controller: ObservationBundle:User:changeAvatar

user_users:
    path: /users
    defaults:
      _controller: ObservationBundle:User:users

user_status:
    path: /{id}/status
    defaults:
      _controller: ObservationBundle:User:reactivate

user_roles:
    path: /{id}/roles
    defaults:
      _controller: ObservationBundle:User:roles

user_sleep:
    path: /sleep
    defaults:
      _controller: ObservationBundle:User:sleep

user_unsleep:
    path: /unsleep/{token}
    defaults:
      _controller: ObservationBundle:User:unsleep
    requirements:
      -token: \.+