user_registration:
    path: /registration
    defaults:
      _controller: ObservationBundle:User:registration

user_login:
    path: /login
    defaults:
      _controller: ObservationBundle:User:login

user_logout:
    path: /logout