user_registration:
    path: /registration
    defaults:
      _controller: ObservationBundle:User:registration

user_login:
    path: /login
    defaults:
      _controller: ObservationBundle:User:login

user_logout:
    path: /logout

user_forgot_password:
    path: /reset
    defaults:
      _controller: ObservationBundle:User:reset

user_link_forgot:
    path: /reset/{token}
    defaults:
      _controller: ObservationBundle:User:resetPassword
      token: \.+

user_profil:
    path: /profil
    defaults:
      _controller: ObservationBundle:User:profil

user_change_password:
    path: /change
    defaults:
        _controller: ObservationBundle:User:changePassword

user_connect:
    path: /connect
    defaults:
        _controller: ObservationBundle:User:connect

user_my_observations:
    path: /my_observations
    defaults:
        _controller: ObservationBundle:User:myObservations

user_observations:
    path: /observations
    defaults:
        _controller: ObservationBundle:User:observations

user_stars:
    path: /stars
    defaults:
        _controller: ObservationBundle:User:stars