user_login:
    path: /login
    defaults:
      _controller: ObservationBundle:User:login
    requirements:
      _method:  GET|POST
user_logout:
    path: /logout
    requirements:
      _method:  GET

user_forgot_password:
    path: /reset
    defaults:
      _controller: ObservationBundle:User:reset
    requirements:
      _method:  GET|POST

user_link_forgot:
    path: /reset/{token}
    defaults:
      _controller: ObservationBundle:User:resetPassword
      token: \.+
    requirements:
      _method:  GET|POST

user_change_password:
    path: /change_password
    defaults:
      _controller: ObservationBundle:User:changePassword
    requirements:
      _method:  GET|POST

user_profil:
    path: /profil
    defaults:
      _controller: ObservationBundle:User:profil
    requirements:
      _method:  GET|POST

user_connect:
    path: /connect
    defaults:
        _controller: ObservationBundle:User:connect
    requirements:
      _method:  GET|POST

user_my_observations:
    path: /my_observations
    defaults:
        _controller: ObservationBundle:User:myObservations
    requirements:
      _method:  GET

user_observations:
    path: /observations
    defaults:
        _controller: ObservationBundle:User:observations
    requirements:
      _method:  GET

user_stars:
    path: /stars
    defaults:
        _controller: ObservationBundle:User:stars
    requirements:
      _method:  GET

user_change_avatar:
    path: /avatar/change
    defaults:
      _controller: ObservationBundle:User:changeAvatar
    requirements:
      _method:  GET|POST

user_users:
    path: /users
    defaults:
      _controller: ObservationBundle:User:users
    requirements:
      _method:  GET

user_status:
    path: /{id}/status
    defaults:
      _controller: ObservationBundle:User:reactivate
    requirements:
      _method:  GET|POST

user_roles:
    path: /{id}/roles
    defaults:
      _controller: ObservationBundle:User:roles
    requirements:
      _method:  GET|POST

user_sleep:
    path: /sleep
    defaults:
      _controller: ObservationBundle:User:sleep
    requirements:
      _method:  GET|POST

user_unsleep:
    path: /unsleep/{token}
    defaults:
      _controller: ObservationBundle:User:unsleep
    requirements:
      -token: \.+
      _method: GET|POST

user_contacts:
    path: /contacts
    defaults:
      _controller: ObservationBundle:User:contacts
    requirements:
      _method:  GET|POST
